version: '2'

services:
  postgres:
    image: 'postgres:9.6'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/theonebot'

volumes:
  postgres:
